### PR TITLE
add check for empty samples and test cases

### PR DESCRIPTION
**Pull request by willi-kappler**
Hi StefanoD,

I've added an additional check for empty samples and also added two test cases: one for empty weights and one for empty samples.

### CODE REVIEW

**Comment by StefanoD** [comment]
Thanks! :)

**Comment by StefanoD** [comment]
Version 0.3.1 published on crates.io

**Comment by willi-kappler** [comment]
Will also add the f32 case then.

**Comment by willi-kappler** [comment]
Oh sorry, haven't seen that you already published a new version. That was fast ;-)

**Comment by StefanoD** [comment]
I didn't add a test case for f32, because the logic is the same, but if you do a pull request, I would accept it, but I wouldn't release a new version, because it doesn't affect the lib for the users.

**Pull request merged**
